### ISSUE TITLE
GitLab PR formatter 

### ISSUE THREAD

**Issue by misteral** [prontolabs/pronto#106]
Messages for PR, not for commit. 
Any plans for this?

**Comment by hannesfostie** [comment]
This exists already afaik, look for `PULL_REQUEST_ID` in the readme :-)

**Comment by mmozuras** [comment]
@hannesfostie only exists for `GitHub`. 

Don't use GitLab myself, but would assume that using GitHub PR Formatter as a starting point, would make it easy to implement this one too :smile:

**Comment by hannesfostie** [comment]
Apologies, I misread!

**Comment by 007lva** [comment]
It will be great.

**Comment by mmozuras** [comment]
@jeroenj maybe you'll take a stab at this? :smile:

**Comment by jeroenj** [comment]
I just had a quick look and from what I can tell it is not supported in [GitLab's API](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/notes.md#merge-requests) right now. I had a quick look at the API code and it isn't in there. So adding this feature would involve writing the necessary code for GitLab, the api wrapper and then pronto.

I don't have a lot of free time on my hands right now, but I do think it's a good idea. Another option might be to create a feature request at GitLab to have the comments on commits shown on the merge request diff page. Then no work in the API, API wrapper or pronto has to be done to support it.

If somebody else decides to add support for it, you might be interested in my MR's/PR's for the current GitLab support:
* https://github.com/NARKOZ/gitlab/pull/88
* https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/137

**Comment by mmozuras** [comment]
Closing in favor of #232.
