### ISSUE TITLE
Runners, limit for sames warnings

### ISSUE THREAD

**Issue by yozgarcia** [prontolabs/pronto#211]
When a file has several warnings of the same type, only a few are shown. this happen with severals runners
ex. with rubocop

class NuevaCosa
  def noFaz
    nada =10
  end
  def noFaz
    nada =10
  end
  def noFaz
    nada =10
  end
  def noFaz
    nada =10
  end
  def noFaz
    nada =10
  end
  def noFaz
    nada =10
  end
  def noFaz
    nada =10
  end
end

when use >>>>> Pronto run -r rubocop  i get this:

Pronto::Rubocop: app/models/nueva_cosa.rb:2 I: Style/MethodName: Use snake_case for method names.
Pronto::Rubocop: app/models/nueva_cosa.rb:5 I: Style/MethodName: Use snake_case for method names.
Pronto::Rubocop: app/models/nueva_cosa.rb:8 I: Style/MethodName: Use snake_case for method names.
Pronto::Rubocop: app/models/nueva_cosa.rb:11 I: Style/MethodName: Use snake_case for method names.

the others lines dont appear

when i run rubocop only i get all:

== app/models/nueva_cosa.rb ==
C:  2:  7: Style/MethodName: Use snake_case for method names.
C:  5:  7: Style/MethodName: Use snake_case for method names.
C:  8:  7: Style/MethodName: Use snake_case for method names.
C: 11:  7: Style/MethodName: Use snake_case for method names.
C: 14:  7: Style/MethodName: Use snake_case for method names.
C: 17:  7: Style/MethodName: Use snake_case for method names.
C: 20:  7: Style/MethodName: Use snake_case for method names.

How do I eliminate this limit for same warnings?

**Comment by mmozuras** [comment]
@yozgarcia could you create a repo that allows reproducing this issue?

Note that pronto doesn't check the whole file. By default, it only cares about changes made in the branch.
