### ISSUE TITLE
Add an option to pass a .pronto.yml config file

### ISSUE THREAD

**Issue by jeroenj** [prontolabs/pronto#226]
In our current setup we use a Docker image to run pronto in a container to run the checks in our CI. Since we have a lot (120+ projects) that should be checked we want to centralise as much of the configs as possible. Because it isn't possible to set the path of a `.pronto.yml` config file (unless I'm overlooking it?) it means the easiest way to use it is to embed it in all our projects.

It looks like the code already is able to support it, but it just needs to get passed to it? (https://github.com/mmozuras/pronto/blob/master/lib/pronto/config_file.rb#L38)

**Comment by mmozuras** [comment]
@jeroenj that's correct. It's _almost_ supported, would accept a pull request adding an option to set a path via a flag 🙂.

**Comment by jeroenj** [comment]
Yeah, my idea was to contribute it as soon as I've got the time for it. 👍 😃
