### ISSUE TITLE
Converting to a GitHub organisation

### ISSUE THREAD

**Issue by mmozuras** [prontolabs/pronto#227]
Hey,

I've decided to consider moving all Pronto related repositories to an organisation. Before I decide to pull the trigger, I'd like to ask for some input. I personally think that it would help organise, maintain and contribute in a better way ✊.

First thing that I've checked:
* [x] Github will automatically redirect the old personal repo to the new org repo.

@mknapik, @doomspork, @jeroenj, @aergonaut, @nicka, @andrey-skat, @nbekirov, @gabealmer: all of you have contributed significant chunks of code to Pronto, so your input would be especially valuable 🙇.

**Comment by doomspork** [comment]
Howdy @mmozuras!  I see no problems with switching to an organization so long as you're happy to do so 😀 

Let me know if there's anything I can do to help.

**Comment by aergonaut** [comment]
Yep I see no problems doing this!

**Comment by nicka** [comment]
Same here, please go ahead 👍

**Comment by jeroenj** [comment]
Sounds great to me. As long as you're okay with it. :)

**Comment by nbekirov** [comment]
That sounds like a great idea. 👍

**Comment by mmozuras** [comment]
Thanks for support! 🙂

And here are some initial ideas for the logo: [1](https://cloud.githubusercontent.com/assets/54526/25452313/e0db7178-2acd-11e7-8757-2db063fdafc3.jpg), [2](https://cloud.githubusercontent.com/assets/54526/25452316/e1035102-2acd-11e7-9cf4-f1a6c4fa7f16.jpg), [3](https://cloud.githubusercontent.com/assets/54526/25452315/e1033cbc-2acd-11e7-8717-75aebd26b8e6.jpg), [4](https://cloud.githubusercontent.com/assets/54526/25452314/e1022840-2acd-11e7-8875-c00968f6b85b.jpg). Drawn up by a good friend. Which do you like? Which conveys Pronto's idea in the best way? Any other ideas on what could be Pronto's logo?

**Comment by doomspork** [comment]
@mmozuras I like #2.   I'll ponder logo ideas over the next few days.  Thanks again for including all of us in the decision making process 😁

**Comment by aergonaut** [comment]
Yeah, I like 2 the most. Conveys the theme of speed the best in my opinion.

**Comment by giedriusr** [comment]
2nd

**Comment by jeroenj** [comment]
I like the first one the most. But I really like the second one too. :)

**Comment by nbekirov** [comment]
I really like #2

**Comment by mmozuras** [comment]
I'll use that drawing of 2 as a temporary avatar until we'll get a proper version of it 😄.

Next problem: `pronto` is taken. `pronto-org`? Not a fan. Anyone has better ideas? 🙂

**Comment by aergonaut** [comment]
Ideas:

- prontissimo
- pronto-rb
- pronto-labs

**Comment by ivanovaleksey** [comment]
I wasn't invited and I don't have any contribution yet (I would like to ☺️ ), but I would vote for the 2nd logo.
`pronto-rb` would be nice organization name.

**Comment by doomspork** [comment]
I prefer `getpronto`, `pronto-labs`, or `pronto-org`.  Albeit a Ruby gem, given that a lot of the runners _are not_ Ruby, I would shy away from `pronto-rb` or `pronto-gem`.

**Comment by mmozuras** [comment]
@doomspork good point about a lot of the runners not being Ruby related 👍.

@aergonaut @doomspork where does `pronto-labs` idea come from? Is `Redis Labs` the inspiration? Or are there more labs out there? 😄

**Comment by doomspork** [comment]
@mmozuras my inspiration came from @aergonaut's suggestion 😁

**Comment by aergonaut** [comment]
Just thinking of other cool-sounding suffixes 😃  I think I like getpronto more than pronto-labs, personally.

**Comment by mmozuras** [comment]
I like `pronto-org` and `pronto-labs` so far the most. It would also be nice to have the domain available 😄.

**Comment by doomspork** [comment]
@mmozuras these are available:

+ pronto-labs.com
+ pronto-labs.io
+ prontolabs.io
+ pronto-org.com
+ pronto-org.io

**Comment by aergonaut** [comment]
👍  for pronto-labs and pronto-labs.io

**Comment by mmozuras** [comment]
@doomspork @aergonaut what are your thoughts and arguments on `prontolabs` & `prontolabs.io` vs. `pronto-labs` & `pronto-labs.io`?

**Comment by doomspork** [comment]
@mmozuras no strong feelings, which do you prefer?

**Comment by jeroenj** [comment]
@mmozuras I'd go with `pronto-labs` & `pronto-labs.io`.

Have you tried contacting the user who has the `pronto` username?

**Comment by mmozuras** [comment]
@jeroenj I haven't, but I'll try 👍

**Comment by jeroenj** [comment]
In case he's willing to give it up I'd go with `getpronto.io`. If not I'd stick with `pronto-labs`. :)

**Comment by mmozuras** [comment]
I went with http://prontolabs.io (set up as redirect) and https://github.com/prontolabs. There's no wrong answer 😄. I think that no dash makes it easier to describe in real life. I also like the consistency with other Labs, like https://github.com/postmanlabs/, https://github.com/awslabs, https://github.com/RedisLabs, which all chose to not have a dash.

I added the second sketch as a temporary logo and moved all my personal repositories to the org.

@aergonaut thanks for the `labs` idea! And thanks everyone for your thoughts and feedback 👍.

Next two steps:
- [ ] figure out the principles for inviting people to the org.
- [ ] figure out the principles for adding pronto related libs/gems/runners (and their owners) to the org.

Thoughts/feedback on those two? Any examples of how other orgs do it? 🙂

**Comment by aergonaut** [comment]
Should you change the attribution in the copyright and LICENSE to something like "Pronto Contributors"?

> figure out the principles for inviting people to the org.

I don't know how Rails/Ember/etc. decide who is added to the core teams, but I think in general members of the org should have a commitment to triaging incoming issues and reviewing Pull Requests.

> figure out the principles for adding pronto related libs/gems/runners (and their owners) to the org.

I think 3rd party runners can stay separate from the org, but you could link them from the list of runners.

**Comment by doomspork** [comment]
I tend to agree with @aergonaut 👍 

> figure out the principles for inviting people to the org.

This is always tough and I've tried different things with the couple of the orgs I'm in.  I personally feel a person needs to demonstrate a commitment to continued participation and support of Pronto; there's a lot of folks out there looking to "collect them all" with regards to org badges on their profile.

As people are added to the organization it'll be important to agree on a process of reviewing, merging, and releasing new features that keeps the overall vision intact; its easy to merge everything that comes through without giving consideration to it's impact on the long term project health and growth.

@mmozuras I believe you should always retained the right to veto features and be the deciding vote in the event of a disagreement amongst contributors.

> figure out the principles for adding pronto related libs/gems/runners (and their owners) to the org.

With [Ueberauth](https://github.com/ueberauth) we only keep packages maintained by the core team in the organization and rely on a Wiki page for third parties.  If someone no longer intends to maintain their project you could certainly take over ownership of it under the umbrella of the organization but I would be hesitant to take on the maintenance burden of them all.

**Comment by mmozuras** [comment]
@aergonaut @doomspork thanks, very valuable thoughts. I'll make a suggestion on principles this week 🙂

I've worked with a designer on a logo. Here's the result:

![pronto_logo_final](https://cloud.githubusercontent.com/assets/54526/26361440/a6642f32-3fe3-11e7-9ac2-5dfe853b5893.jpg)

Any thoughts on which one (or ones?) to use?

**Comment by aergonaut** [comment]
Oh wow, all very nice. For the organization's avatar image, I like the orange and white "P" on the black background.

**Comment by ivanovaleksey** [comment]
Really cool! I like 2nd line from the bottom (with orange bars). They can be used as long and short version.

**Comment by doomspork** [comment]
I agree with @aergonaut & @ivanovaleksey.  The singular white P, orange lines, and blackground really pops.

The rest are awesome too, kudos to the designer!

**Comment by jeroenj** [comment]
I like those ones the most too. I guess a white background with a black P with orange lines would be an option too for the avatar?

**Comment by mmozuras** [comment]
@aergonaut @ivanovaleksey @doomspork @jeroenj thanks for your valuable opinions! I've now changed the avatar to a new beautiful one. I'll give the compliments to the designer 🙇.

**Comment by doomspork** [comment]
@mmozuras you can probably close this now 😀

**Comment by mmozuras** [comment]
@doomspork soon 😄 

I've added `welcome` repo to serve as the central hub for org related things: https://github.com/prontolabs/welcome.

**Comment by doomspork** [comment]
Looking good @mmozuras 👍
