### ISSUE TITLE
GitLab pull request formatter

### ISSUE THREAD

**Issue by ivanovaleksey** [prontolabs/pronto#232]
Hi @mmozuras,

thank you for the awesome gem!

I use it with GitLab instance.
I noticed that only commit formatter exists for GitLab. But GitLab API contains [endpoints](https://docs.gitlab.com/ee/api/notes.html#merge-requests) to work with comments on pull requests (merge requests as they call them).

Is it possible to enable pull request commenting for GitLab (maybe there are some restrictions I don't know about) ?
If it is I would happily start to working on it.

**Comment by ivanovaleksey** [comment]
Seems like I understand the problem now.
Merge request [API](https://docs.gitlab.com/ee/api/notes.html#create-new-merge-request-note) allows to create a note for the entire merge request. We can't specify particular line of code.
And comment for commit [API](https://docs.gitlab.com/ee/api/commits.html#post-comment-to-commit) allows to do per-line commenting.

😞

**Comment by mikes01** [comment]
Hi, the Merge request API should have per-line commenting soon, it is already implemented https://gitlab.com/gitlab-org/gitlab-ce/issues/20901
It will be released in 9.2 version at May 21.

**Comment by ivanovaleksey** [comment]
@mikes01 cool, thank you! 
Then I will continue work on PR after API updates.

**Comment by ivanovaleksey** [comment]
Looks like implementing this feature will also close #106

**Comment by ivanovaleksey** [comment]
It seems like the GitLab issue was moved to 9.3 milestone which has due date on June, 21.

**Comment by ivanovaleksey** [comment]
@mmozuras to be honest I didn't read all the discussions because the are huge enough.
As I can see 9.2 (initial milestone for the issue) still [has very much to do](https://gitlab.com/gitlab-org/gitlab-ce/milestones/36). And it should be closed 3 days ago, on May 21 😕

**Comment by ivanovaleksey** [comment]
And it is moved to 9.4 😞

**Comment by siebertm** [comment]
This API seems to be implemented in 10.8 release :-D https://docs.gitlab.com/ce/api/discussions.html

**Comment by Strnadj** [comment]
PR https://github.com/prontolabs/pronto/pull/308  ;)

**Comment by vkotovv** [comment]
Looks like it can be closed now, resolved by #351 MR

**Comment by ivanovaleksey** [comment]
@vkotovv thanks for pointing this out. Currently I am not using Pronto, so I can't actually test behaviour.
I will close the issue. If there would be any problems write a comment to reopen.
