### ISSUE TITLE
Support HTTParty 0.15

### ISSUE THREAD

**Issue by singpolyma-shopify** [prontolabs/pronto#250]

**Comment by lipanski** [comment]
@mmozuras can you pretty please release a new version after https://github.com/prontolabs/pronto/commit/96089533df1f3711bb89f63855bb809d59843a5f

we were just about to use pronto in our app, but stumbled upon an httparty downgrade which we don't want.

**Comment by mmozuras** [comment]
@lipanski released with [v0.9.5](https://github.com/prontolabs/pronto/releases/tag/v0.9.5).
