### ISSUE TITLE
Problem with running pronto in a pre-commit hook

### ISSUE THREAD

**Issue by grodowski** [prontolabs/pronto#263]
Hey!

I have run into a problem with setting up pronto as a `pre-commit` git hook. 

Given there are new rubocop warnings and I have the below script in `.git/hooks/pre-commit`...

```sh
#!/bin/bash
bundle exec pronto run --staged --runner rubocop --exit-code
```

Pronto does what is expected and shows the rubocop warnings when I run:

```sh
git add .
git commit -m "test"
```

But unfortunately I get no rubocop output and a false-positive exit status 0 on

```sh
git commit -am "test"
```

This is strange and I've been trying to understand the reason. Traced it back to the below line, where `rugged` returns an empty diff for the `staged` option (just in the second use case).

https://github.com/prontolabs/pronto/blob/e97cb2b648206bd51b1a4784a282f474f9eb51e2/lib/pronto/git/repository.rb#L15

Any help would be welcome!

Edit: I am using pronto 0.9.5

**Comment by mmozuras** [comment]
@grodowski thanks for reporting the issue! 🙇 

Managed to reproduce it by following the steps you've outlined. Tried a couple of other cases and it shows warnings when using `--staged` with:

```
git add .
git commit -am "test"
```

It also shows error when using `--unstaged` flag with:

```
git commit -am "test"
```

That was an AHA moment for me. One workaround that works: having two pre-commit scripts. One for `--unstaged` flag, the other one for `--staged`.

@prontolabs/core I also wonder if we should support an option that covers both `--unstaged` and `--staged` with a single flag? Or support combining multiple flags? Thoughts?

**Comment by printercu** [comment]
Just faced this issue. Using master to resolve Rugged::TreeError.
@mmozuras do you have any updates on how to make it work with both `--staged --index` given?

As a workaround I run pronto second time for new files:
```bash
bundle exec pronto run --index --exit-code

new_files=`git diff --cached --name-status | (grep -E "^[A]" || true) | cut -f2-`
[ -n "$new_files" ] && bundle exec pronto run --staged --exit-code
```

**Comment by grodowski** [comment]
@mmozuras I've been working on a coverage tool that integrates with git (and Pronto), which combines `staged` + `unstaged` [by default, like this](https://github.com/grodowski/undercover/blob/976698da3a2e64e912dd8c2c8053d20b514de94d/lib/undercover/changeset.rb#L68-L81). I might be able to port this to `pronto` as a new flag or a combination of the two.
