### ISSUE TITLE
i cant find any directory named lcmtypes/mav_ins_t.h from pronto

### ISSUE THREAD

**Issue by adamrek** [prontolabs/pronto#273]
i want to run the project of andybarry/flight , but when i finish all step, i meet a problem :
#include "lcmtypes/mav_ins_t.h" // from pronto
how to figure it ?

**Comment by doomspork** [comment]
@adamrek can you provide anymore details?  Is there a sample project available we can use to reproduce the issue?

**Comment by adamrek** [comment]
@doomspork i want to run the project      http://github.com/andybarry/flight     and   i follow the step     https://github.com/andybarry/flight/wiki

**Comment by adamrek** [comment]
@doomspork   when i start the  install pronto   and  use the command      make -j    i  meet the problem

**Comment by adamrek** [comment]
@doomspork   and  i clone the libbot  , i also meet some problem ..  i dont know how to tell the detail in english.

**Comment by adamrek** [comment]
i follow the step  install pronto 

cd pronto
git checkout 8f8a38bbc9c1552d99b496c194a9df726e1b5f67
cd ..
make -j


 the result:   引用不是一个树：8f8a38bbc9c1552d99b496c194a9df726e1b5f67

**Comment by mknapik** [comment]
https://github.com/andybarry/flight/wiki/Install-Pronto

https://github.com/andybarry/flight links to https://github.com/oxfordrobotics/pronto-distro which contains https://github.com/openhumanoids/pronto as a subrepository.
Can't find the git ref but I'm pretty sure you're referring to a wrong project.

**Comment by adamrek** [comment]
@mknapik  thank you，i will follow your suggestion and try  tonight

**Comment by adamrek** [comment]
@mknapik     i input       make -j    , but i cant connect google .... because i m in China .

**Comment by adamrek** [comment]
i clone the pronto from  https://github.com/oxfordrobotics/pronto-distro  and when i  use  the command  : make -j  . i should connect the lcm.google.com   to  download some files,  but  the reaction is   404 not found , how can i download these files  in the new website?

**Comment by adamrek** [comment]
i need downloead   the two files  named    lcm 1.0.0/configure   and  lcm 1.0.0/makefile

**Comment by mknapik** [comment]
@adamrek Try opening an issue on https://github.com/oxfordrobotics/pronto-distro and consulting with maintainers. https://github.com/prontolabs/pronto is a different project.
`prontolabs/pronto` is a code quality tool written in Ruby and I guess you're looking for a C++ project.
