### ISSUE TITLE
How can I use pronto for Angular and Java

### ISSUE THREAD

**Issue by amo-wtag** [prontolabs/pronto#286]
Hello Alturist,

I want to integrate pronto for my Java and Angular github branch, but I cannot find any solution for doing this...

Would you please guide how can I integrate pronto in Angular and Java?
Is it possible to integrate in Angular and Java?

Thanks in advance,
Amit

**Comment by doomspork** [comment]
Howdy @amo-wtag!  We don't provide hands on support or setup instructions at this time.  You should be able to find everything you need in the README to run Pronto for both Java and JavaScript.  We even have a section of articles and tutorials: https://github.com/prontolabs/pronto#articles

You'll need to start by identifying which runners apply to your project: https://github.com/prontolabs/pronto#runners

Some to consider:

+ pronto-eslint 
+ pronto-jshint
+ pronto-jscs

It doesn't look like we have any runners specific to Angular or Java — yet!  Once you create them we'll be sure to add them to the list.
