### ISSUE TITLE
Change default gitlab api endpoint

### ISSUE THREAD

**Issue by micjabbour** [prontolabs/pronto#297]
[GitLab is removing API v3](https://about.gitlab.com/2018/06/01/api-v3-removal-impending/). I think that we only need to change [the default gitlab api endpoint](https://github.com/prontolabs/pronto/blob/e5e7f822c7958718aa16b82bd555256ed1f24404/lib/pronto/config_file.rb#L19) to point to `https://gitlab.com/api/v4`. I have done a quick test locally and nothing seems to break (but I wanted to make sure before creating a PR)...

**Comment by doomspork** [comment]
@micjabbour please open a PR 👍
