### ISSUE TITLE
Support for Ruby Critic?

### ISSUE THREAD

**Issue by berniechiu** [prontolabs/pronto#300]
I wonder if there's any support for [https://github.com/whitesmith/rubycritic](https://github.com/whitesmith/rubycritic)

I can start working on it if it's one of the milestone and compatible for the `pronto` gem, thanks.

**Comment by mknapik** [comment]
Each runner is a separate gem and most of each are independent projects: https://github.com/prontolabs/pronto#runners
Feel free to create it if you think such runner would be useful.
That being said, it seems the functionality or `rubycritic` and `pronto` overlap a little bit. Does `rubycritic` provide any extra rules except for the ones which come from it's dependencies? I can see `rubycritic` is using `flay` and `flog` of which `flay` already has a `pronto` runner.

**Comment by berniechiu** [comment]
I see thanks, I'll look into it.
