### ISSUE TITLE
Release new gem version

### ISSUE THREAD

**Issue by panjan** [prontolabs/pronto#312]
Hi,

First of all, thanks for the great gem! ❤️ 

The last version was released [more than a year ago](https://rubygems.org/gems/pronto/versions). Are there any plans for the next release?

**Comment by aergonaut** [comment]
cc @prontolabs/core

**Comment by kubamahnert** [comment]
Simply tagging the version in git would also suffice. This way, when we want to use newer code than the one released in 0.9.5, we have to reference your commit hashes directly. That's not really pretty..

**Comment by siebertm** [comment]
we're running into the same issue as @dinhhuydh, also https://github.com/aergonaut/pronto-goodcheck/issues/1

Our solution for now is to use the `master` directly in our Gemfile. Not ideal but "works"

**Comment by dinhhuydh** [comment]
@siebertm Same here.

**Comment by williampollet** [comment]
Same issue here, `react_on_rails` depends on `rainbow`  `3.0`.

**Comment by djpate** [comment]
:+1:  is the project dead?

**Comment by doomspork** [comment]
@djpate there are commits from just a few days ago, no the project is not dead, that's a foolish thing to ask without even evaluating the project. The project owner, with RubyGem access, has been preoccupied with personal matters. The other maintainers and I on @prontolabs/core have been working very hard to keep things moving.

Please be mindful and considerate of the people who dedicate their free time to making these tools. We are all humans at the end of the day and things do unfortunately come up that have to take priority over open source.

**Comment by mmozuras** [comment]
I've just pushed a new gem version - [v0.10.0](https://github.com/prontolabs/pronto/releases/tag/v0.10.0). 

I haven't been a good steward of this project for the last year. Over this month I'll try to consider options on how to make it better. Thanks everyone for your patience! 🙇

**Comment by siebertm** [comment]
Thanks @mmozuras!

> Over this month I'll try to consider options on how to make it better

If this'd be a issue on the tracker, would you mind mentioning me? We're relying on pronto in our core workflows, so we'd like to be on top of things here, no matter what the outcome!
