### ISSUE TITLE
Octokit::BadGateway 502 - Server Error

### ISSUE THREAD

**Issue by agibralter** [prontolabs/pronto#315]
For PRs with many linting violations, it seems that the GitHub API is choking using the `github_pull_request_review_formatter`. Should there be a maximum payload size?

**Comment by agibralter** [comment]
Yeah, so I just confirmed that reducing the payload of this particular payload allowed the PR review from pronto to go through. I'm not sure if this is the number of comments, or if there's a particular file with too many comments. I'm not entirely sure how to debug this any further though because the 502 error from GitHub is pretty opaque.

**Comment by agibralter** [comment]
(I contacted GitHub support about this—will report back if I hear anything.)

**Comment by agibralter** [comment]
This is what I got back:
![image](https://user-images.githubusercontent.com/1079/46293821-7ed2a100-c562-11e8-87ae-5774082beff1.png)

**Comment by mikegee** [comment]
I think you can configure the maximum number of offenses to report back to Github since this PR: https://github.com/prontolabs/pronto/pull/127

Maybe try dialing that down?

**Comment by agibralter** [comment]
Ah good call. I think I'll close this as it's not clear what we can do on the pronto side to change this. Perhaps Github (and thus octokit) will impose payload limits in which case pronto may need to adjust its use of octokit... but until then we can't really do anything.

**Comment by kofronpi** [comment]
This is still an issue as I first installed pronto today. And the comment threshold seemed to be < 150
I'm using a personal API token for a company repo, is that why ? It finally went through for 18 comments though...
