### ISSUE TITLE
Add example images for formatters

### ISSUE THREAD

**Issue by deiga** [prontolabs/pronto#322]
It's currently quite a hassle to figure out what Formatter to use as there isn't a comprehensive documentation or example images of the output.

Please add example images of Formatter outputs :)

**Comment by doomspork** [comment]
@deiga this would be a great addition, would you be willing to contribute those changes?

**Comment by doomspork** [comment]
Howdy @deiga thought I'd check in again, would this be something you're willing to contribute? Otherwise let's close this issue.

**Comment by deiga** [comment]
@doomspork I don't see me prioritising this in the next few months to get this done.

**Comment by doomspork** [comment]
Sounds good, we'll close this.
