### ISSUE TITLE
Make Pronto::Git::Patch#new_file_path public for plugin authors to use

### ISSUE THREAD

**Issue by apiology** [prontolabs/pronto#366]
It looks like the GitHub reporter (at least) won't report on an issue if we provide the absolute path in the Message object.  This is, for instance, what pronto-rubocop does: https://github.com/prontolabs/pronto-rubocop/blob/master/lib/pronto/rubocop/offense_line.rb#L19

Unfortunately, the convenience method to pull this is private:
https://github.com/prontolabs/pronto/blob/master/lib/pronto/git/patch.rb#L42

It'd be nice if this were public.

**Comment by doomspork** [comment]
@apiology I see no problem with this, would you please submit a PR with appropriate test coverage?
