### ISSUE TITLE
Release new gem version

### ISSUE THREAD

**Issue by ashkulz** [prontolabs/pronto#376]
We're in the same situation as #312 -- it's been a year since a release was made. Is there anything the community can do to help make that happen?

cc @mmozuras

**Comment by oksanka-blaze** [comment]
+1

**Comment by ylecuyer** [comment]
+1

**Comment by RGBD** [comment]
@mmozuras, pinging you once again.

**Comment by RGBD** [comment]
@doomspork, @aergonaut ?

**Comment by AxelTheGerman** [comment]
😞 I was just trying to integrate `pronto` into our CI workflow, had an issue installing `rugged`, seeing there are newer versions available and no releases in over a year here.

Seems like development on master branch has slowed too - going to have to find something else 😢

**Comment by RGBD** [comment]
@AxelTheGerman , I ended up having a separate Gemfile and rubocop config in .pronto directory
then in .gitlab-ci.yml you can do
```
- bundle exec --gemfile .pronto/Gemfile pronto run -f gitlab_mr -c $SHA1
```
this way you don't need rugged in production

**Comment by doomspork** [comment]
I have gotten access to my RubyGems account restore and will start working through new releases. 

I would love to find some additional contributors for the Pronto org, right now the volume of requests far exceeds the bandwidth of myself. For those interested, please feel free to reach out to me or pass along this tweet if you know anyone who could be a good addition: https://twitter.com/doomspork/status/1275089086341017600

**Comment by ylecuyer** [comment]
Great news thanks :+1:

**Comment by ashkulz** [comment]
@doomspork: I'm willing to contribute (_use it at work_) -- what kind of help would be most beneficial e.g. issue triage, PRs etc?

**Comment by doomspork** [comment]
Issue triage and helping get PRs merged would be a great first step and a tremendous help. 

We can work together to go through each repo, get things merged, version updated, and I'll get new gems published.

**Comment by Intrepidd** [comment]
Hi, just to let you know, due to the old thor dependency in the last released version, pronto will not work for rails 6.1.0

I'm also willing to help sort things out for the next release

**Comment by ashkulz** [comment]
I've been merging PRs, but I've had no luck in reaching out to @doomspork / @mmozuras for the release to RubyGems.

**Comment by ashkulz** [comment]
I've been granted permissions to publish to RubyGems by @doomspork, will try to release by this weekend.

**Comment by doomspork** [comment]
@ashkulz I will finish adding you to the remaining gems tomorrow, I seem to have been throttled for adding you and @aergonaut to them 😆

**Comment by ashkulz** [comment]
I haven't gotten time to complete the release, will try to do it over this weekend :see_no_evil:

**Comment by arielscherman** [comment]
@ashkulz Any updates on the release? I have come across incompatibility issues with `Thor` when using rails 6.1.1 and even though using `master` branch would solve it, latest release `(0.10.0)` is:

```ruby
# gemspec
s.add_runtime_dependency('thor', '~> 0.20.0')
```

Which is conflicting with Rails 6.1.1 on `thor (~> 1.0)`

**Comment by ashkulz** [comment]
I've released the new version to RubyGems.
