### ISSUE TITLE
Dependencies on gitlab and github should not be defined in the gemspec

### ISSUE THREAD

**Issue by solnic** [prontolabs/pronto#382]
First of all, thanks for pronto! It helps us significantly and we enjoy using it.

Now the problem: given that a pronto user may or may not be using GitHub and/or GitLab, the client gems *should not be specified in the gemspec* because they are not core dependencies.

My specific case is that I use GitHub, so I don't want to have GitLab client gem in my dependencies because it can, and it actually did, cause dependency issues.

One way to solve this problem is to add require statements that rescue from `LoadError` and provide a meaningful error.

**Comment by mknapik** [comment]
I agree however the code is coupled so it would be quite a refactoring.
Also, I'm wondering if such change constitutes as a minor or a major one in terms of versioning.

**Comment by solnic** [comment]
I'd say this should result in just moving things around a bit and changing that one place where you require client 3rd-party gems.

Technically speaking, it would be a breaking change since people would have to add client gems to their Gemfiles (assuming they don't have them already listed for other reasons than using pronto).

**Comment by emilebosch** [comment]
Yes I was talking about this too in #373 !

**Comment by solnic** [comment]
@emilebosch woah not sure how I missed that! I'm gonna close this one as it's clearly a duplicate.
