### ISSUE TITLE
Problem with version 4.22 of octokit

### ISSUE THREAD

**Issue by adis-io** [prontolabs/pronto#427]
[Authentication changes with Octokit v4.22 causes failures with legacy Faraday versions](https://github.com/octokit/octokit.rb/issues/1392)

Maybe it's worth to add note about it? I've spent couple of hours to debug this problem and that's it – problem was with octokit 🤦‍♂️

**Comment by ashkulz** [comment]
@adis-io considering `faraday` is an indirect dependency, I'm not sure this belongs here in pronto.
