### ISSUE TITLE
Release new gem version

### ISSUE THREAD

**Issue by jj4me** [prontolabs/pronto#428]
Hi,

First of all, thanks for the great gem!

The last version was released more than a year ago. Are there any plans for the next release?

I'd really like to use the new --workdir option and have updated dependencies!

**Comment by exoego** [comment]
I am also waiting for a new release.
Because I am hitting a dependency version incompatibility with the latest [pronto-undercover](https://github.com/grodowski/pronto-undercover) 0.2.0, which added branch coverage support.

My workaround: use `git:` in Gemfile.
```ruby
gem 'pronto', git: 'https://github.com/prontolabs/pronto'
```

**Comment by ashkulz** [comment]
Release `0.11.1` has been pushed to RubyGems.
