### ISSUE TITLE
Refator the way formatters are loaded to make easy to include custom formatter

### ISSUE THREAD

**Issue by emilio2hd** [prontolabs/pronto#451]
## Context
I was talking with a friend once about how pronto can create a huge noise adding too many comments on github, when a PR is big.
By the time, we're discussing how other tool was nice posting the comments as github annotation leaving the comments just for developers.
So, I've thought how it would be nice if pronto could do the same thing.

## Workaround
Investigating the code, I noticed that the json formatter wouldn't be enough. I ended up creating this (not yet released) gem [pronto-annotations_formatter](https://github.com/emilio2hd/pronto-annotations_formatter), which produces a json to be consumed by [pronto-annotate-action](https://github.com/emilio2hd/pronto-annotate-action).
I wasn't happy because I had to do some Monkeypatch stuff to modify the `Pronto::Formatter::FORMATTERS`, which I think it's really dangerous, but it was the only way I could think.

One could argue "you could've just used a rake task". Well, yeah but I want to shared this solution because more people could benefit from it, and I think nothing is better than a Gem to share this.

## Refactoring
After analysing the code again, I thought on how Devise loads its strategies. The same pattern could be applied to formatter.
I branched out the repo and implemented the pattern.
Please check the PR https://github.com/prontolabs/pronto/pull/450.

Now, with this solution I don't need to use Monkeypatch in my Gem, I just need to do:
```ruby
module Pronto
  module Formatter
    class MyCustomFormatter < Pronto::Formatter::Base
      def format(messages, _repo, _patches)
        # Do stuff
      end
    end
  end
end

Pronto::Formatter.add('mycustom', Pronto::Formatter::MyCustomFormatter)
```

**Comment by ashkulz** [comment]
@emilio2hd please let me know if you want me to make a release for the above tools to depend on -- I'd be eager to try it at $WORK as well :grin:

**Comment by emilio2hd** [comment]
Hey @ashkulz yahoo! Let's do it!
Thank you!

**Comment by ashkulz** [comment]
@emilio2hd [pronto 0.11.2](https://rubygems.org/gems/pronto/versions/0.11.2) released to RubyGems :tada:

**Comment by emilio2hd** [comment]
@ashkulz Done! released latest version removing the monkey patch :tada:
