### ISSUE TITLE
Allow Octokit 8.0

### ISSUE THREAD

**Issue by pbstriker38** [prontolabs/pronto#453]
Octokit v8.0.0 was released with changes to the way pull request comments are created. They have removed the deprecated position argument and replaced it with `line`

https://github.com/octokit/octokit.rb/releases/tag/v8.0.0
https://github.com/octokit/octokit.rb/pull/1566

https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#create-a-review-comment-for-a-pull-request

**Comment by ashkulz** [comment]
[`0.11.3`](https://rubygems.org/gems/pronto/versions/0.11.3) has been released to RubyGems. Publishing future versions should be simpler due to implementation of Trusted Publishing workflow (c7007deaa060395911ba039604655d6d08fae556) :grin:
